name: Feature request
description: Suggest an idea for this project.
title: "[Feature] "
labels: ["\U0001F680 Feature"]
# assignees:
#   - stone-zeng
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit you issue using the following template!
        By opening this issue you confirm that you have searched for similar issues/PRs here already.
  - type: textarea
    id: feature-request
    attributes:
      label: Feature Request
      description: "Is your feature request related to a problem? Please describe."
      placeholder: |
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: "Add any other context or screenshots about the feature request here."
      placeholder: |
        Add any other context or screenshots about the feature request here.
    validations:
      required: false
